version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://colorpuzzle-backend:5000

    restart: always
    networks:
      - colorpuzzle-network

  backend:
    container_name: colorpuzzle-backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/colorpuzzle
    restart: always
    networks:
      - colorpuzzle-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - colorpuzzle-network

volumes:
  mongodb_data:

networks:
  colorpuzzle-network:
    driver: bridge
